[build]
    command = "npm run build"
    environment = {SENDGRID_API_KEY = "",SENDGRID_FROM_EMAIL = "", HOOK_REBUILD_TOKEN = "", DIRECTUS_URL = ""}
    functions = "functions/"
    publish = "dist/"

[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/builders/:splat"

[functions."build"]
schedule = "@daily"