[build]
command = "npm start"
environment = { HOOK_REBUILD_TOKEN = "628e00b2f5095567a2f82fcb", DIRECTUS_TOKEN = "", NETLIFY_EMAILS_PROVIDER = "sendgrid", NETLIFY_EMAILS_PROVIDER_API_KEY = "" }
functions = "functions"
publish = "dist"
