[build]
    command = "npm run build"
    environment = {SENDGRID_API_KEY = "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",SENDGRID_FROM_EMAIL = "website@sexpression.org.uk", HOOK_REBUILD_TOKEN = "629b494abf1f716c3e72259c", DIRECTUS_URL = "sexpression.directus.app"}
    functions = "functions/"
    publish = "dist/"

[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/builders/:splat"

[functions."build"]
schedule = "@daily"