[build]
    command = "npm run build"
    environment = {AIRTABLE_API_KEY = "keyXbPYpiRPqVt47G",AIRTABLE_BASE_ID = "app5BQoGuuWeGljLz",SENDGRID_API_KEY = "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",SENDGRID_FROM_EMAIL = "website@sexpression.org.uk",NODE_VERSION = "16.5.0"}
    functions = "functions/"
    publish = "dist/"

[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/:splat"

# [dev]
#     command = "npm start"