[build]
    environment = {AIRTABLE_API_KEY = "keyXbPYpiRPqVt47G",AIRTABLE_BASE_ID = "app5BQoGuuWeGljLz",SENDGRID_API_KEY = "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",NODE_VERSION = "16.5.0"}
    functions = "functions/"

[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/:splat"


# [dev]
#     command = "npm start"