backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: Pages
    name: "Page"
    folder: "src/"
    slug: "{{slug}}"
    create: true
    fields:
    - { default: container_is-max-desktop, label: Layout, name: layout, widget: hidden }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }