backend:
  name: git-gateway
  branch: dev
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/"
    slug: "{{slug}}"
    create: true
    fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "container_is-max-desktop.njk" }
    - { label: "Name", name: "name", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Last Modified", name: "lastmodified", widget: "hidden", default: "", date_format: "DD.MM.YYYY", time_format: "HH:mm", picker_utc: true }
    - { label: "Body", name: "body", widget: "markdown" }
  - name: "opportunities"
    label: "Opportunities"
    folder: "src/opportunities"
    slug: "{{slug}}"
    create: true
    fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "opportunity.njk" }
    - { label: "Tags", name: "tags", widget: "hidden", default: "opportunity" }
    - { label: "Name", name: "name", widget: "string" }
    - { label: "Positions", name: "positions", widget: "number", default: 1, value_type: "int", min: 1, max: 9  }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Deadline", name: "deadline", widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: "HH:mm", picker_utc: true }
    - { label: "Charity Jobs URL", name: "link", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }